<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-08-08
 * Time: 09:39
 */

namespace authall\platforms;

class Baidu extends Base
{
    private $code;

    public function init()
    {
//        parent::init(); // TODO: Change the autogenerated stub
    }

    public function setCode($code){
        if (empty($code)){
            throw new \Exception('code not be empty');
        }
        $this->code = $code;
        return $this;
    }

    public function getCode(){
        return $this->code;
    }

    public function getOpenId()
    {
//        parent::getOpenId(); // TODO: Change the autogenerated stub
        $options['form_params'] = [
            'code' => $this->getCode(),
            'client_id' => $this->getAppId(),
            'sk' => $this->getAppSecret(),
        ];

        $options['form_params'] = $this->getParams();

        try {
            $this->response = $this->client->request('POST', $this->getAuthUrl(), $options);
        }catch (\Exception $e){
            throw $e;
        }

        $ret = $this->client->getContent();
        $ret = json_decode($ret,true);
        return $ret;
    }
}