<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-08-08
 * Time: 09:19
 */

namespace authall\platforms;

class Device extends Base
{
    private $deviceId;

    public function init()
    {
//        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getDeviceId()
    {
        return $this->deviceId;
    }

    /**
     * @param $deviceId
     * @throws \Exception
     */
    public function setDeviceId($deviceId)
    {
        if (empty($deviceId)){
            throw new \Exception('deviceId not be empty');
        }
        $this->deviceId = $deviceId;
    }



    public function getOpenId()
    {
//        parent::getOpenId(); // TODO: Change the autogenerated stub
        $ret = ['deviceId' => $this->getDeviceId()];
        return $ret;
    }

    /**
     * @throws \Exception
     */
    public function getResponse()
    {
//        return parent::getResponse(); // TODO: Change the autogenerated stub
        throw new \Exception('no response');
    }

}