<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-08-08
 * Time: 09:40
 */

namespace authall\platforms;

class Meizu extends Base
{
    private $access_token;

    public function init()
    {
//        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getAccessToken()
    {
        return $this->access_token;
    }

    /**
     * @param $access_token
     * @throws \Exception
     */
    public function setAccessToken($access_token)
    {
        if (empty($access_token)){
            throw new \Exception('access_token not be empty');
        }
        $this->access_token = $access_token;
    }



    public function getOpenId()
    {
//        parent::getOpenId(); // TODO: Change the autogenerated stub
        $options['query'] = [
            'access_token' => $this->getAccessToken()
        ];

        try {
            $this->response = $this->client->request('GET', $this->authUrl, $options);
        }catch (\Exception $e){
            throw $e;
        }

        $ret = $this->client->getContent();
        $ret = json_decode($ret,true);
        return $ret;
    }

}