<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-08-08
 * Time: 09:19
 */

namespace authall\platforms;

class Oppo extends Base
{
    private $pkgName;
    private $token;

    public function init()
    {
//        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getPkgName()
    {
        return $this->pkgName;
    }

    /**
     * @param mixed $pkgName
     */
    public function setPkgName($pkgName): void
    {
        $this->pkgName = $pkgName;
    }

    /**
     * @return mixed
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * @param mixed $token
     */
    public function setToken($token): void
    {
        $this->token = $token;
    }

    public function getOpenId()
    {
//        parent::getOpenId(); // TODO: Change the autogenerated stub
        $options['header'] = ['Content-Type' => 'application/json'];
        $params = [
            'pkgName' => $this->getPkgName(),           //游戏包名
            'token' => $this->getToken(),              //登录时获得的token
            'timeStamp' => getMillisecond(),           //时间戳，毫秒，取当前时间值
            'appKey' => $this->getAppId(),
            'appSecret' => $this->getAppSecret(),
        ];

        $sign = $this->getSignatureString($params);

        $params['sign'] = $sign;
        $params['version'] = 'v1.0.0';

        $options['query'] = $params;

        try{
            $this->client->request('GET',$this->getAuthUrl(),$options);
        }catch (\Exception $e){
            throw $e;
        }

        $ret = $this->client->getContent();
        $ret = json_decode($ret,true);
        return $ret;
    }

    /**
     * 生成签名
     * @param $params
     * @return string
     */
    private function getSignatureString($params){
        ksort($params);

        foreach ($params as $k => $v){
            $list[] = $k.'='.$v;
        }
        $sign = implode('&',$list);
        $sign = strtoupper(md5($sign));
        return $sign;
    }


}