<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-08-08
 * Time: 09:40
 */

namespace authall\platforms;

class Qtt extends Base
{
    private $platform;
    private $ticket;

    public function init()
    {
//        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getOpenId()
    {
//        parent::getOpenId(); // TODO: Change the autogenerated stub
    }

}