<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-08-08
 * Time: 09:40
 */

namespace authall\platforms;

class Qtt extends Base
{
    private $platform = 'qtt';
    private $ticket;

    public function init()
    {
//        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getOpenId()
    {
//        parent::getOpenId(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * @param mixed $platform
     */
    public function setPlatform($platform)
    {
        $this->setParams(['platform' => 'qtt']);
    }

    /**
     * @return mixed
     */
    public function getTicket()
    {
        return $this->ticket;
    }

    /**
     * @param $ticket
     * @throws \Exception
     */
    public function setTicket($ticket)
    {
        if (empty($ticket)){
            throw new \Exception('ticket not by empty');
        }
        $this->setParams(['ticket' => $ticket]);
    }



}