<?php
/**
 * Create by PhpStorm
 * Author Aaron z
 * Date: 2019-08-08
 * Time: 09:40
 */

namespace authall\platforms;

class Sqq extends Base
{
    private $code;

    public function init()
    {
//        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * @param $code
     * @throws \Exception
     */
    public function setCode($code)
    {
        if (empty($code)){
            throw new \Exception('code not be empty');
        }

        $this->setParams(['code' => $code]);
    }



}